
# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

jobs:
  - job: TriggerTasks
    displayName: 'Trigger Tasks'
    steps:
      - script: |

          # Check if tasks are completed
          if tasks_completed:
            echo "All tasks are completed."
            - script: |
                echo "Marking tasks as done..."
                az devops work item update --id 123 --fields "System.State=Closed"
              displayName: 'Mark Tasks as Done'
          else:
            echo "Tasks are not completed. Going back to previous step."
            # Go back to previous step
            - script: |
                echo "Going back to previous step..."
                bash path/to/previous-step.sh
              displayName: 'Go Back to Previous Step'

        displayName: 'Check Task Completion'
